### ISSUE TITLE
multiple people & threshold not working 

### ISSUE THREAD

**Issue by Ethan0104** [ecd1012/rpi_pose_estimation#1]
Hello, I just followed your set up instructions and tried out the pose estimation script. I noticed 2 problems. First, it seems like the program always thinks that there is one person in the screen, which means if there is no people in the screen, it will give me random points, and if there are more than 1 person, it only generates 1 set of keypoints. 

I also attempted to fix the random keypoints problem by tuning the threshold, but that didn't work and I discovered later that the variable min_conf_threshold is never used. 

So how can I change the code to detect multiple people and also incorporate the threshold? Any help is appreciated.

**Comment by ecd1012** [comment]
Hey Ethan! Thanks for looking through the code and finding issues! Just to get a minimum viable product working for Pose Estimation, I did the following:

1. Didn't use the score threshold
2. Only Implemented Single Pose Estimation

In hindsight, 1.) was a bad idea - and I will make a commit to fix that. 2.) The multi-person pose estimation problem is more difficult and out of the scope of what I was trying to do. If you want to take a shot at it yourself, I suggest looking at the following:

- https://blog.tensorflow.org/2018/05/real-time-human-pose-estimation-in.html
- https://arxiv.org/pdf/1803.08225.pdf

Hope this helps!

**Comment by ecd1012** [comment]
Just made a commit to add in score thresholding:

- https://github.com/ecd1012/rpi_pose_estimation/commit/268e1fddcd6b0092b13f4d9801ff52264a1b72dd

If you want to try implementing multi person pose estimation, I can add you as a contributor to the repository :)
