### ISSUE TITLE
get_py_requirements.sh not in repo

### ISSUE THREAD

**Issue by MauiJerry** [ecd1012/rpi_pose_estimation#2]
The instructions say to follow directions 3-9 from the driving repo, one of which says to run the above named shell script.  This is NOT in this repository.
work around is to copy/download it from the other repo and run.

**Comment by ecd1012** [comment]
@MauiJerry Sorry about that, just added it to this repo too!
https://github.com/ecd1012/rpi_pose_estimation/commit/45d0c2bcd7d9464615f6222ff217889c154937b4
